# Generated by Django 5.1.5 on 2025-01-23 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trading.vendor', verbose_name='supplier'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='products',
            field=models.ManyToManyField(related_name='products', to='trading.product', verbose_name='products'),
        ),
    ]
