# Generated by Django 5.1.5 on 2025-01-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_vendor_supplier_alter_vendor_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='launched_at',
            field=models.DateField(verbose_name='launched product date'),
        ),
    ]
